### ISSUE TITLE
Any intention to support windows platform?

### ISSUE THREAD

**Issue by Shin-ing** [mehran-prs/snip#6]

**Comment by mehran-prs** [comment]
Hi @Shin-ing 

I've not tested it on Windows, but it should work, you can test it, just install it through `go` command:
```bash
go install -ldflags "-X main.Version=main -X main.Date=`date +'%FT%TZ%z'`"  github.com/mehran-prs/snip@main
```

And the other instructions for auto-completion... should be the same on windows if you're using either one of zsh | bash | powershell | fish as your shell.
